In [1]:
#importing Libraries
import selenium
import pandas as pd
import numpy as np
import time
from bs4 import BeautifulSoup

#importing selenium webdriver
from selenium import webdriver

#for press the enter
from selenium.webdriver.common.keys import Keys

#importing the requried exception which needs to handle
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException

#importing requests
import requests

#importing regex
import re

#for right click button
from selenium.webdriver import ActionChains

1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [22]:
#importing the driver from the crome
driver=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the web url:
url=('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.get(url)
time.sleep(5)

## creating empty lists for scraping data
video_rank1=[]
videoName1=[]
Uploader1=[]
video_views1=[]
uploaddate1=[]

time.sleep(4)
#scraping the video-Rank
rank1=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
for i in rank1:
    if i.text is None :
        video_rank1.append("_") 
    else:
        video_rank1.append(i.text.replace('.',''))

time.sleep(4)
#scraping the video-Name
videon1=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
for i in videon1:
    if i.text is None:
        videoName1.append("_")
    else:
        videoName1.append(i.text)

time.sleep(4)
#scraping the Uploader details
uplodr1=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
for i in uplodr1:
    if i.text is None:
        Uploader1.append("_")
    else:
        Uploader1.append(i.text)  

time.sleep(4)
#scraping the total views
views1=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
for i in views1:
    if i.text is None:
        video_views1.append("_")
    else:
        video_views1.append(i.text)  

time.sleep(4)
#scraping the Upload date
date1=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
for i in date1:
    if i.text is None:
        uploaddate1.append("_")
    else:
        uploaddate1.append(i.text)   

time.sleep(3)
#creating the dataframe
df1=pd.DataFrame({})
df1['Rank']=video_rank1[:30]
df1['Video Name']=videoName1[:30]
df1['Artist']=Uploader1[:30]
df1['Upload Date']=uploaddate1[:30]
df1['Views(in billions)']=video_views1[:30]


#printing dataframe
df1

,Rank,Video Name,Artist,Upload Date,Views(in billions)
0,1,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,"June 17, 2016",9.02
1,2,"""Despacito""[24]",Luis Fonsi,"January 12, 2017",7.46
2,3,"""Johny Johny Yes Papa""[25]",LooLoo Kids,"October 8, 2016",5.58
3,4,"""Shape of You""[26]",Ed Sheeran,"January 30, 2017",5.40
4,5,"""See You Again""[27]",Wiz Khalifa,"April 6, 2015",5.19
5,6,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,"January 31, 2012",4.45
6,7,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.37
7,8,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.31
8,9,"""Uptown Funk""[33]",Mark Ronson,"November 19, 2014",4.24
9,10,"""Gangnam Style""[34]",Psy,"July 15, 2012",4.13
10,11,"""Phonics Song with Two Words""[36]",ChuChu TV,"March 6, 2014",4.02
11,12,"""Sugar""[37]",Maroon 5,"January 14, 2015",3.51
12,13,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.48
13,14,"""Sorry""[39]",Justin Bieber,"October 22, 2015",3.45
14,15,"""Roar""[40]",Katy Perry,"September 5, 2013",3.39
15,16,"""Counting Stars""[41]",OneRepublic,"May 31, 2013",3.35
16,17,"""Thinking Out Loud""[42]",Ed Sheeran,"October 7, 2014",3.29
17,18,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.18
18,19,"""Dark Horse""[44]",Katy Perry,"February 20, 2014",3.11
19,20,"""Faded""[45]",Alan Walker,"December 3, 2015",3.10
20,21,"""Shake It Off""[46]",Taylor Swift,"August 18, 2014",3.08
21,22,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.08
22,23,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.07
23,24,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.07
24,25,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.03
25,26,"""Mi Gente""[51]",J Balvin,"June 29, 2017",2.95
26,27,"""Perfect""[52]",Ed Sheeran,"November 9, 2017",2.90
27,28,"""Axel F""[53]",Crazy Frog,"June 16, 2009",2.90
28,29,"""Waka Waka (This Time for Africa)""[54]",Shakira,"June 4, 2010",2.89
29,30,"""Hello""[55]",Adele,"October 22, 2015",2.86

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [11]:
#importing the driver from the crome
driver2=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the web url:
url=('https://www.bcci.tv/')
driver2.get(url)
time.sleep(3)

#click on the international fixture
img_click=driver2.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]')
img_click.click()
time.sleep(2)

#going to the image page
fixture=driver2.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')
fixture.click()
time.sleep(4)

#defining the variable
Matchtitle2=[]
Series2=[]
Place2=[]
Date2=[]
Time2=[]

#fetching the Match title
mat2=driver2.find_elements_by_xpath('//strong[@class="fixture__name fixture__name--with-margin"]')
for i in mat2:
    if i.text is None :
        Matchtitle2.append("_") 
    else:
        Matchtitle2.append(i.text)
        
#fetching the series
sea2=driver2.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]')
for i in sea2:
    if i.text is None :
        Series2.append("_") 
    else:
        Series2.append(i.text)        

#fetching the place
pal2=driver2.find_elements_by_xpath('//p[@class="fixture__additional-info"]//span')
for i in pal2:
    if i.text is None :
        Place2.append("_") 
    else:
        Place2.append(i.text) 
        
#fetching the date
dat2=driver2.find_elements_by_xpath('//div[@class="fixture__full-date"]')
for i in dat2:
    if i.text is None :
        Date2.append("_") 
    else:
        Date2.append(i.text[:6].replace('\n',' '))
        
#fetching the time        
tim2=driver2.find_elements_by_xpath('//span[@class="fixture__time"]')
for i in tim2:
    if i.text is None :
        Time2.append("_") 
    else:
        Time2.append(i.text.replace('\n',' '))
        
time.sleep(5)
#creating the dataframe
df2=pd.DataFrame({})
df2['Match title']=Matchtitle2
df2['Series']=Series2 
df2['Place']=Place2  
df2['Date']=Date2  
df2['Time']=Time2  
#printing dataframe
df2

,Match title,Series,Place,Date,Time
0,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",04 AUG,15:30 IST
1,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",12 AUG,15:30 IST
2,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",25 AUG,15:30 IST
3,4th Test,ENGLAND V INDIA 2021,"The Oval, London",02 SEP,15:30 IST
4,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",10 SEP,15:30 IST

3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [34]:
#importing the driver from the crome
driver3=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the web url:
url=('https://www.guru99.com/')
driver3.get(url)
time.sleep(5)

#going to the image page
img_click=driver3.find_element_by_xpath('/html/body/footer/div/div[1]/div/div/div/div/div/div[2]/div[2]/div/div/div/a/i')
img_click.click()
time.sleep(5)

#going to the exception page
excep_click=driver3.find_element_by_xpath('/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]/a')
excep_click.click()
time.sleep(9)

## creating empty lists for scraping data
exception_nm3=[]
description3=[]


time.sleep(4)
#scraping the exception name
excep3=driver3.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
for i in excep3:
    if i.text is None :
        exception_nm3.append("_") 
    else:
        exception_nm3.append(i.text.replace('.',''))

time.sleep(4)
#scraping the exception desc
desc3=driver3.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
for i in desc3:
    if i.text is None:
        description3.append("_")
    else:
        description3.append(i.text) 
        
        
time.sleep(5)
#creating the dataframe
df3=pd.DataFrame({})
df3['Exception Name']=exception_nm3[1:]
df3['Descrpition']=description3  [1:]

#printing dataframe
df3

,Exception Name,Descrpition
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandlerUnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [10]:
#importing the driver from the crome
driver4=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the web url:
url=('http://statisticstimes.com/')
driver4.get(url)
time.sleep(5)

#click on economy
img_click=driver4.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
img_click.click()
#time.sleep(10)

#clieck on india
ind_click=driver4.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
ind_click.click()
time.sleep(5)

#click on the state ecomony
eco_click=driver4.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
eco_click.click()
time.sleep(3)

#defining the variable
rank4=[]
state4=[]
GSDP_current4=[]
DSDP_current41=[]
share4=[]
GDP4=[]

#fetching the state Rank
rnk4=driver4.find_elements_by_xpath('//td[@class="data1"]')
for i in rnk4:
    if i.text is None :
        rank4.append("_") 
    else:
        rank4.append(i.text)

#fetching the state Name
st4=driver4.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[2]')
for i in st4:
    if i.text is None :
        state4.append("_") 
    else:
        state4.append(i.text)

#fetching the GSDP at current price (19-20)
GSDP4=driver4.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[3]')
for i in GSDP4:
    if i.text is None :
        GSDP_current4.append("_") 
    else:
        GSDP_current4.append(i.text)

#fetching the GSDP at current price (18-19)
GSDP41=driver4.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[4]')
for i in GSDP41:
    if i.text is None :
        DSDP_current41.append("_") 
    else:
        DSDP_current41.append(i.text)

#fetching the share (18-19)
SHR4=driver4.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[5]')
for i in SHR4:
    if i.text is None :
        share4.append("_") 
    else:
        share4.append(i.text)

#fetching the GDP($ billion)
gdp=driver4.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[6]')
for i in gdp:
    if i.text is None :
        GDP4.append("_") 
    else:
        GDP4.append(i.text)
        
        
time.sleep(5)
#creating the dataframe
df4=pd.DataFrame({})
df4['State Rank']=rank4[:33]
df4['State Name']=state4[:33]
df4['GSDP at current price (19-20)']=GSDP_current4[:33]
df4['GSDP at current price (18-19)']=DSDP_current41[:33]
df4['Share(18-19)']=share4[:33]
df4['GDP($ billion)']=GDP4[:33]

#printing dataframe
df4

,State Rank,State Name,GSDP at current price (19-20),GSDP at current price (18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

5.Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [20]:
#importing the driver from the crome
driver5=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the web url:
url=('https://github.com/')
driver5.get(url)
time.sleep(5)

#click on sign in
img_click5=driver5.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/div[2]/div[2]/a')
img_click5.click()
time.sleep(5)

#entering the login id
login_dt=driver5.find_element_by_id('login_field')
login_dt.send_keys('rahulksingh1211@gmail.com')
time.sleep(2)

#entering password
password5=driver5.find_element_by_id('password')
password5.send_keys('Mee@1995')
time.sleep(2)

#Click on submit
submit5=driver5.find_element_by_xpath('/html/body/div[3]/main/div/div[4]/form/div/input[12]')
submit5.click()
time.sleep(3)

#click on explore
Explore5=driver5.find_element_by_xpath('/html/body/div[4]/div/div/div/aside/a')
Explore5.click()
time.sleep(3)

#click on the repositaries
Tranding5=driver5.find_element_by_xpath('/html/body/div[4]/main/div[1]/nav/div/a[3]')
Tranding5.click()
time.sleep(3)

#fetching the reposisiteris details
reopes_url5=[]
for i in driver5.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]//a'):
    reopes_url5.append(i.get_attribute('href'))
    

time.sleep(3)
#Defining the variables
rep_title5=[]
discription5=[]
contributor5=[]
language5=[]

for i in reopes_url5:
    driver5.get(i)
    time.sleep(1)
    
     #fetching the title
    try:
        title5 = driver5.find_element_by_xpath('//strong[@class="mr-2 flex-self-stretch"]//a')
        rep_title5.append(title5.text)
    except NoSuchElementException:
        rep_title5.append('_')
        
        #feching the description
    try:
        desc5 = driver5.find_element_by_xpath('//p[@class="f4 mt-3"]')
        discription5.append(desc5.text)
    except NoSuchElementException:
        discription5.append('_')
        
        #feching the contributor details 
    try:
        count=driver5.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        contributor5.append(count.text)
    except NoSuchElementException:#handling no such element exception
        contributor5.append('_')
        
         #feching the language details
    try:
        lage5 = driver5.find_element_by_xpath('//span[@class="color-text-primary text-bold mr-1"]')
        language5.append(lage5.text)
    except NoSuchElementException:
        language5.append('_')  

time.sleep(3)
#creating the dataframe
df5=pd.DataFrame({})
df5['Title']=rep_title5
df5['Description']=discription5
df5['Contributer']=contributor5
df5['Language']=language5

#printing dataframe
df5

,Title,Description,Contributer,Language
0,lkmpg,The Linux Kernel Module Programming Guide (upd...,13,TeX
1,openpilot,openpilot is an open source driver assistance ...,209,C++
2,ML-For-Beginners,"12 weeks, 25 lessons, 50 quizzes, classic Mach...",52,Jupyter Notebook
3,system-design-primer,Learn how to design large-scale systems. Prep ...,110,Python
4,Web-Dev-For-Beginners,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",82,JavaScript
5,docs,The open-source repo for docs.github.com,763,JavaScript
6,modern-unix,A collection of modern/faster/saner alternativ...,9,_
7,reviewdog,🐶 Automated code review tool integrated with a...,65,Go
8,ShuiZe_0x727,信息收集自动化工具,_,Python
9,axum,Ergonomic and modular web framework built with...,13,Rust
10,Python-Practise-Problems,_,_,_
11,vue-admin-beautiful-pro,"🚀🚀🚀vue3,vue3.0,vue,vue3.x,vue.js,vue后台管理,admin...",5,Vue
12,awesome-for-beginners,A list of awesome beginners-friendly projects.,260,_
13,alertmanager,Prometheus Alertmanager,226,Go
14,freqtrade,"Free, open source crypto trading bot",160,Python
15,gin,Gin is a HTTP web framework written in Go (Gol...,321,Go
16,sheetjs,📗 SheetJS Community Edition -- Spreadsheet Dat...,125,JavaScript
17,prowler,Prowler is a security tool to perform AWS secu...,111,Shell
18,virtual-environments,GitHub Actions virtual environments,155,PowerShell
19,sigma,Generic Signature Format for SIEM Systems,239,Python
20,mmcv,OpenMMLab Computer Vision Foundation,122,Python
21,azure-sdk-for-net,This repository is for active development of t...,"1,002",C#
22,voicevox,_,5,TypeScript
23,awesome-java,"A curated list of awesome frameworks, librarie...",306,_
24,Rubeus,Trying to tame the three-headed dog.,19,C#

6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [133]:
#importing the driver from the crome
driver6=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the web url:
url=('https://www.billboard.com/')
driver6.get(url)
time.sleep(5)

#click on sign in
img_click6=driver6.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/nav/ul/li[3]/a')
img_click6.click()
time.sleep(10)

#define the data 
current_rank6=[]
album_name6=[]
band6=[]
last_week6=[]
peak_rank6=[]
onboard6=[]

for i in driver6.find_elements_by_xpath('//span[@class="chart-element__rank__number"]'):
    current_rank6.append(i.text)

for i in driver6.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]'):
    album_name6.append(i.text)
    
for i in driver6.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]'):
    band6.append(i.text)     

lastw6=driver6.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
for i in lastw6:
    if i.text is None :
        last_week6.append("_") 
    else:
        last_week6.append(i.text)

peakw6=driver6.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
for i in peakw6:
    if i.text is None :
        peak_rank6.append("_") 
    else:
        peak_rank6.append(i.text)  
        
week6=driver6.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for i in week6:
    if i.text is None :
        onboard6.append("_") 
    else:
        onboard6.append(i.text)   
        
        
time.sleep(3)
#creating the dataframe
df6=pd.DataFrame({})
df6['Currunt Rank']=current_rank6
df6['Album name']=album_name6
df6['Artist']=band6
df6['Last week rank']=last_week6
df6['Peak Rank']=peak_rank6
df6['Onboard time']=onboard6

#printing dataframe
df6

,Currunt Rank,Album name,Artist,Last week rank,Peak Rank,Onboard time
0,1,Butter,BTS,7,1,9
1,2,Good 4 U,Olivia Rodrigo,2,1,10
2,3,Levitating,Dua Lipa Featuring DaBaby,4,2,42
3,4,Stay,The Kid LAROI & Justin Bieber,3,3,2
4,5,Kiss Me More,Doja Cat Featuring SZA,5,3,15
...,...,...,...,...,...,...
95,96,Build A Bitch,Bella Poarch,84,56,10
96,97,30,Pop Smoke Featuring Bizzy Banks,-,97,1
97,98,You Should Probably Leave,Chris Stapleton,91,90,3
98,99,"Jealousy, Jealousy",Olivia Rodrigo,87,24,9
99,100,Cold Beer Calling My Name,Jameson Rodgers Featuring Luke Combs,95,95,3

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [99]:
#importing the driver for Chrome
driver7=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the webpage using url 
url=('https://www.naukri.com/')
driver7.get(url)
time.sleep(3)

#click on the recruters
#recruter_click7=driver7.find_element_by_xpath('/html/body/div[1]/div/div/ul[1]/li[2]/a')
#recruter_click7.click()
#time.sleep(4)

#click on the recruters
input7=driver7.find_element_by_xpath('//input[@class="sugInp"]')
input7.send_keys('Data science')
time.sleep(4)

#click on the recruters
search7=driver7.find_element_by_xpath('//div[@class="search-btn"]')
search7.click()
time.sleep(10)


#click on the recruters
later7=driver7.find_element_by_xpath('/html/body/div[3]/span[1]')
later7.click()
time.sleep(4)

#click on the recruters
recruter_click7=driver7.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div')
recruter_click7.click()
time.sleep(8)

#Switching the active widow
driver7.switch_to.window(driver7.window_handles[1])
time.sleep(5)

#scrolling page the slowing
total_height = int(driver7.execute_script("return document.body.scrollHeight"))
for i in range(1, total_height, 10):
    driver7.execute_script("window.scrollTo(0, {});".format(i))

time.sleep(3)

#clicking on the showall option
driver7.find_element_by_xpath('/html/body/div[3]/div[1]/div[1]/div[2]/div/div/div[1]/div[3]/a').click()
time.sleep(4)  


#defining the variable
Name7=[]
Designation7=[]
Company7=[]
Skillshire7=[]
Location7=[]
compny7=[]

#fetching the Book Name
Nm7=driver7.find_elements_by_xpath('//span[@class="fl ellipsis"]')
for i in Nm7:
    if i.text is None :
        Name7.append("_") 
    else:
        Name7.append(i.text)
        
#fetching the Book Name
deg7=driver7.find_elements_by_xpath('//span[@class="ellipsis clr"]')
for i in deg7:
    if i.text is None :
        Designation7.append("_") 
    else:
        Designation7.append(i.text) 
        
#fetching the Book Name
loc7=driver7.find_elements_by_xpath('//small[@class="ellipsis"]')
for i in loc7:
    if i.text is None :
        Location7.append("_") 
    else:
        Location7.append(i.text)
        
#fetching the Book Name
com7=driver7.find_elements_by_xpath('//a[@class="ellipsis"]')
for i in com7:
    if i.text is None :
        Company7.append("_") 
    else:
        Company7.append(i.text)
        
for i in range(1,len(Company7),2):
    compny7.append(Company7[i])
    
#fetching the Book Name
skl7=driver7.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
for i in skl7:
    if i.text is None :
        Skillshire7.append("_") 
    else:
        Skillshire7.append(i.text)
        
time.sleep(5)
#creating the dataframe
df7=pd.DataFrame({})
df7['name']=Name7
df7['Designation']=Designation7
df7['Location']=Location7
df7['Company']=compny7
df7['Skills they hire for']=Skillshire7


#printing dataframe
df7

,name,Designation,Location,Company,Skills they hire for
0,Santhosh Kumar,Associate Manager Human Resources,Chennai,Maveric Systems,"It Recruitment, Campus Recruitment, Campus Hir..."
1,Gauri Bhosle,Human Resources,Mumbai,TCRC,"Operation Executive, Jr. Chemist/ Chemist, Aud..."
2,Sanghvi,Company Recruiter,Ahmedabad,Primacy Systems Pvt Ltd,"Marketing, Sales, Plastic, Aluminium, Metal, S..."
3,Rohit Khandelwal,Company Recruiter,Jaipur,PADHAI HELP PRIVATE LIMITED,Marketing
4,Neha Pandey,Company Recruiter,Gurgaon,Ingenious E-Brain Solutions Private Limited,"B.tech, Operations, Business Development, Busi..."
5,Vinita Raut,Company Recruiter,Pune,Xpansion HR Solutions Private Limited,"Bde, Accounting, Education Counseling, Sales, ..."
6,Sanjay Desai,Human Resource Manager,Noida,Samsung,Communication Skills Relationship Building Lea...
7,Susheel Sonar,Human Resources,Mumbai,Rubicon Research,"Manufacturing, Product Development, Pharma, Dr..."
8,Debjani Ghosh,Human Resource Manager,Kolkata,Matrix Media Solutions Pvt. Ltd.,Software Development
9,BALA Sakthivelmuthu,Company Recruiter,Madurai,E Vel,"Html, Css, Javascript, Ui Development, Java, A..."
10,Reena Dwivedi,Human Resource Manager,Varanasi / Banaras,NDS Jewels Pvt Ltd.,"housekeeping, Accounts Receivable, maintenance..."
11,Prerna Mohan,Company Recruiter,Delhi,Prerna Mohan Design Studio,"Interiors, Interior Designing, Interior Decora..."
12,Nitika Pharmaceutical Specialities,Company Recruiter,Nagpur,Nitika Pharmaceutical Specialities Pvt Ltd.,"Business Development, Business Analysis, Proje..."
13,Ashok Kumar Subramani,Company Recruiter,Chennai,MURUGAPPA MANAGEMENT SERVICES,area sales manager /financial sector/candidate...
14,Darshan Thakkar,Company Recruiter,Ahmedabad,GMDT Marine &amp; Industrial Engineering...,"Sales, Business Development, Marketing, Manage..."
15,HR,Human Resources,Kolkata,Crescentek,Developers
16,Kusum Chaudhary,Human Resources,Delhi,Chadha Industries Pvt. Ltd.,"gm-sales, Manager Sales, analyst, Business Ana..."
17,Prarit Gupta,Human Resource Manager,Delhi,HMS Relations Management,"Counter Sales, Sales"
18,Raghu Hrexecutive,Human Resource manager,Bengaluru / Bangalore,IQs soft,"Java/J2ee ( Core Java, Struts, Hibernate, Serv..."
19,Take jobs,Human Resources,Delhi,Take Jobs,"tally, Bank Reconciliation, billing, electrica..."
20,iNFIN Technologies,Human Resources,Chandigarh,Infin Software Technologies Pvt. Ltd,"Technical, PHP, Web Development, Web Technolog..."
21,Punit Kumar Bhidodiya,Human Resource Manager,Indore,Exatip Technologies,"Software Development, Business Development"
22,Ishan Ahmed,Human Resource Manager,Delhi,Jute Wonders Unlimited,Back Office
23,Sreekanth Menon,Human Resources,Ahmedabad,Sterlite Technologies Ltd. Elitecore,"C++, Java/j2ee, C, Networking, Radius, Diamete..."
24,Abhishek,Human Resource Manager,Hyderabad / Secunderabad,Infosys Technology,"Sap Abap, Sap Basis, Sap Fico, Sap Bi, java, C..."
25,TechCube IT Services Pvt Ltd,Human Resource Manager,Mohali,TechCube IT Services Pvt Ltd,Skills- Technical Troubleshooting / Sales / Up...
26,Ms Paridhi,Human Resource Manager,Indore,Exaalgia IT Solutions,"Web Designing, Seo, Content Writing, SEO, Web ..."
27,Fatte Chand Soni,Human Resource Generalist,Jaipur,Tetraskelion Softwares (P) Ltd,".Net, Java, PHP, Android, Testing, IOS, Web an..."
28,Koustav Bose,human resource manager,Mumbai,KKR BOSE DESIGN SERVICES PVT LTD,Ravit
29,Vaishambi Saxena,Human Resources,Bengaluru / Bangalore,22Feet Tribal Worldwide (DDB Worldwide),"Magento, PHP, Content, Design, DotNet, BD"
30,Mohammad Ikram,Human Resources,Lucknow,Team Hr,"It Recruitment, Sales Management, Selling, Pro..."
31,Be Tuned Solutions,Human Resource Manager,Mohali,Be-Tuned Solutions,"Content Writing, Content Development, Technica..."
32,Prerna Kashyap,Human Resource Manager,Mumbai,CoconutEvent,"English Literature, Copy Writing, Content Writ..."
33,Sunil Joshi,Human Resource Manager,Udaipur,"Ravi infra- Build Projects Private limited,","BDM/ BDO, Branch Manager, Senior Branch manage..."
34,Stella,Human Resources,Chennai,Treselle Software Pvt Ltd,"Java, Database, Front End, Big Data, Cloud Com..."
35,Pranav Varia,Human Resource Manager,Surat,Smart Technospace Pvt Ltd,"Project Management, Sharp Supervision, Leaders..."
36,Emma Rodrigues,Human Resource Manager,Mumbai,Sahil International,"Marketing, Customer Service, Finance, Telecom,..."
37,Sonal Sharma,Human Resource Manager,Pune,Paragyte Technologies,"java, support, ui designer/developer, Java Scr..."
38,Sita Chhetri,Human Resource Manager,Nepal - (Kathmandu),Sarbottam Cement Pvt. Ltd. / Laxmi Steels...,"Erection Commissioning, Stores, Installation, ..."
39,Nikhil Bhardwaj,Regional HR Manager,Kolkata,Larsen And Toubro,"Thermodynamics, Heat Transfer, Product Quality..."
40,sumit patel,Human Resources,Ahmedabad,airtel,"Technology Head, tester, manager, php, joomla,..."
41,Vibhuti Bhatt,Human Resources,Ahmedabad,Gujarat Ambuja Exports limited,"Good Communication Skill, Confident Personalit..."
42,Pushkar Gupta,Human Resource Manager,Delhi,Nityo Infotech,"Myntra, Redbus, Digital Vidya, Accolite Softwa..."
43,Anjali Gupta,Human Resource Manager,Gurgaon,Reliance Communications,"Software Development, Technical, It, Web Desig..."
44,katrina Dikoster,Regional HR Manager,Hyderabad / Secunderabad,Cambridge Learning System,"Education Industry, Educational Sales, Educati..."
45,shalini gupta,Regional HR Manager,Delhi,Cambridge Learning System,"Web Designing, Education, Educational Sales, E..."
46,Pradeep Naik,Human Resources,Bengaluru / Bangalore,Akamai Technologies,"Internet Technologies, Media Streaming, Inform..."
47,K Gayaj,Human Resource Manager,Bengaluru / Bangalore,HCG Cancer Care,"health care services, Oncologist, Center Manag..."
48,Ms Chitra Doshi,Human Resource Manager,Ahmedabad,Rasson Energy India Pvt. Ltd.,"Procurement, Supply Chain, Engineer, Marketing..."
49,Neela barad,Human Resource Manager,Ahmedabad,WebPixel Technologies,"Business Development, Post Sales, Cold Calling..."

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [22]:
#importing the driver for Chrome
driver8=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the webpage using url 
url=('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
driver8.get(url)
time.sleep(3)

#defining the variable
title8=[]
Author8=[]
volume8=[]
publiser8=[]
genre8=[]

#fetching the Book Name
tit8=driver8.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in tit8:
    if i.text is None :
        title8.append("_") 
    else:
        title8.append(i.text)
        
#fetching the Author Name
aur8=driver8.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in aur8:
    if i.text is None :
        Author8.append("_") 
    else:
        Author8.append(i.text)

#fetching the volume
vol8=driver8.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in vol8:
    if i.text is None :
        volume8.append("_") 
    else:
        volume8.append(i.text)

        
#fetching the publiser Name
pub8=driver8.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in pub8:
    if i.text is None :
        publiser8.append("_") 
    else:
        publiser8.append(i.text)
        
#fetching the genre
gen8=driver8.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in gen8:
    if i.text is None :
        genre8.append("_") 
    else:
        genre8.append(i.text)        
        
time.sleep(5)
#creating the dataframe
df8=pd.DataFrame({})
df8['Book name']=title8
df8['Author name']=Author8
df8['Volumes sold']=volume8
df8['Publisher']=publiser8
df8['Genre']=genre8


#printing dataframe
df8

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [42]:
#importing the driver for Chrome
driver9=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the webpage using url 
url=('https://www.imdb.com/list/ls095964455/')
driver9.get(url)
time.sleep(4)


#defining the variable
Name9=[]
Yearspan9=[]
Genre9=[]
Runtime9=[]
Ratings9=[]
Votes9=[]

#fetching the Name
Nm9=driver9.find_elements_by_xpath('//h3[@class="lister-item-header"]//a')
for i in Nm9:
    if i.text is None :
        Name9.append("_") 
    else:
        Name9.append(i.text)

#fetching the Yearspan
yr9=driver9.find_elements_by_xpath('//h3[@class="lister-item-header"]/span[2]')
for i in yr9:
    if i.text is None :
        Yearspan9.append("_") 
    else:
        Yearspan9.append(i.text)
        

#fetching the Genre
gen9=driver9.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[5]')
for i in gen9:
    if i.text is None :
        Genre9.append("_") 
    else:
        Genre9.append(i.text)        

#fetching the Runtime
run9=driver9.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[3]')
for i in run9:
    if i.text is None :
        Runtime9.append("_") 
    else:
        Runtime9.append(i.text) 
        
#fetching the Ratings
rat9=driver9.find_elements_by_xpath('//div[@class="ipl-rating-widget"]/div/span[2]')
for i in rat9:
    if i.text is None :
        Ratings9.append("_") 
    else:
        Ratings9.append(i.text)
        
#fetching the Votes count
vot9=driver9.find_elements_by_xpath('//p[@class="text-muted text-small"]/span[2]')
for i in vot9:
    if i.text is None :
        Votes9.append("_") 
    else:
        Votes9.append(i.text) 
        
#seprating the vote count        
Votesact9=[]
for i in range(1,len(Votes9),2):
    Votesact9.append(Votes9[i])
    
    
time.sleep(4)
#creating the dataframe
df9=pd.DataFrame({})
df9['Name']=Name9
df9['Year span']=Yearspan9
df9['Genre']=Genre9
df9['Run time']=Runtime9
df9['Ratings']=Ratings9
df9['Votes']=Votesact9

#printing dataframe
df9

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,844,730"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"882,924"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"884,038"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"265,543"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"226,586"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,951"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,641"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"171,295"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,450"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"194,610"

10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [152]:
#importing the driver for Chrome
driver10=webdriver.Chrome(r'D:\Datatrained\Web Scrapping\chromedriver.exe')

#opening the webpage using url 
url=('https://archive.ics.uci.edu/ml/index.php')
driver10.get(url)
time.sleep(4)

#click on the recruters
click10=driver10.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a')
click10.click()
time.sleep(4)

#defining the variable
Datasetname10=[]
Datatype10=[]
Task10=[]
Attribute10=[]
Noofinstances10=[]
Noofattribute10=[]
Year10=[]
Datatype110=[]
data_t1=[]


#fetching the Name
dt10=driver10.find_elements_by_xpath('//p[@class="normal"]//b')
for i in dt10:
    if i.text is None :
        Datasetname10.append("_") 
    else:
        Datasetname10.append(i.text)

#fetching the all the details
datat10=driver10.find_elements_by_xpath('//p[@class="normal"]')
for i in datat10:
    if i.text is None :
        Datatype110.append("_") 
    else:
        Datatype110.append(i.text) 
        
#saving all the data in a list       
data_t1=Datatype110[9:]
        
#seprating the Data type        
for i in range(0,len(data_t1),7):
    Datatype10.append(data_t1[i])

#seprating the Task
for i in range(1,len(data_t1),7):
    Task10.append(data_t1[i])

#seprating the Attribute type   
for i in range(2,len(data_t1),7):
    Attribute10.append(data_t1[i])

#seprating the No of instances  
for i in range(3,len(data_t1),7):
    Noofinstances10.append(data_t1[i])

#seprating the No of attribute
for i in range(4,len(data_t1),7):
    Noofattribute10.append(data_t1[i])  

#seprating the No of Year    
for i in range(5,len(data_t1),7):
    Year10.append(data_t1[i]) 

time.sleep(4)
#creating the dataframe
df10=pd.DataFrame({})
df10['Dataset name']=Datasetname10
df10['Data type']=Datatype10[:588]
df10['Task']=Task10
df10['Attribute type']=Attribute10
df10['No of instances']=Noofinstances10
df10['No of attribute']=Noofattribute10
df10['Year']=Year10

#printing dataframe
df10

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021